name: Release package
on:
  push:
    branches:
      - main
      - alpha
      - beta
      - next
      - next-major

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Yarn install
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Yarn install
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test
  release:
    name: Release
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Yarn install
        run: yarn install --frozen-lockfile
      - name: Initialise the NPM config
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Initialise the Git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Release
        run: yarn release --ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
